#!/usr/bin/env php
<?php

require __DIR__.'/../../../../init.php';
require __DIR__.'/../vendor/autoload.php';

array_shift( $argv );
echo (new OneCS\App())->run( array_shift( $argv ), $argv ), PHP_EOL;
