echo 'VIRTUAL MACHINE 129 INFORMATION'
echo 'ID                  : 129'
echo 'NAME                : m-debian8-vone-template - vOne-129'
echo 'USER                : oneadmin'
echo 'GROUP               : oneadmin'
echo 'STATE               : ACTIVE'
echo 'LCM_STATE           : BOOT'
echo 'RESCHED             : No'
echo 'HOST                : vOne'
echo 'CLUSTER ID          : 100'
echo 'CLUSTER             : vOne-Cluster-BTK'
echo 'START TIME          : 05/14 22:55:04'
echo 'END TIME            : -'
echo 'DEPLOY ID           : -'
echo 'VIRTUAL MACHINE MONITORING'
echo 'PERMISSIONS'
echo 'OWNER               : um-'
echo 'GROUP               : ---'
echo 'OTHER               : ---'
echo 'VM DISKS'
echo ' ID DATASTORE  TARGET IMAGE                               SIZE      TYPE SAVE'
echo '  0 -          hda    CONTEXT                             -/-       -       -'
echo 'VM NICS'
echo ' ID NETWORK              BRIDGE       IP              MAC'
echo '  0 btk-inet - vOne      btk-inet     185.66.68.5     02:00:b9:42:44:05'
echo 'SECURITY'
echo 'NIC_ID NETWORK                   SECURITY_GROUPS'
echo '     0 btk-inet - vOne           0'
echo 'SECURITY GROUP   TYPE     PROTOCOL NETWORK                       RANGE'
echo '  ID NAME                          VNET START             SIZE'
echo '   0 default     OUTBOUND ALL'
echo '   0 default     INBOUND  ALL'
echo 'VIRTUAL MACHINE HISTORY'
echo 'SEQ HOST            ACTION             DS           START        TIME     PROLOG'
echo '  0 vOne            none               -1  05/14 22:55:18   0d 00h07m   0h00m00s'
echo 'USER TEMPLATE'
echo 'DESCRIPTION="vCenter Template imported by OpenNebula from Cluster vOne"'
echo 'HYPERVISOR="vcenter"'
echo 'KEEP_DISKS_ON_DONE="NO"'
echo 'LOGO="images/logos/debian.png"'
echo 'PUBLIC_CLOUD=['
echo '  TYPE="vcenter",'
echo '  VM_TEMPLATE="4231104e-378d-8b85-4568-3debc88b72e3" ]'
echo 'SCHED_REQUIREMENTS="NAME=\"vOne\""'
echo 'SUNSTONE=['
echo '  NETWORK_SELECT="NO" ]'
echo 'USER_INPUTS=['
echo '  CPU="O|fixed|| |1",'
echo '  MEMORY="O|fixed|| |1024",'
echo '  VCPU="O|fixed|| |1" ]'
echo 'VCENTER_DATASTORE="NAS4"'
echo 'VIRTUAL MACHINE TEMPLATE'
echo 'AUTOMATIC_DS_REQUIREMENTS="\"CLUSTERS/ID\" = 100"'
echo 'AUTOMATIC_REQUIREMENTS="(CLUSTER_ID = 100) & !(PUBLIC_CLOUD = YES) | (PUBLIC_CLOUD = YES & (HYPERVISOR = vcenter))"'
echo 'CONTEXT=['
echo '  DISK_ID="0",'
echo '  ETH0_CONTEXT_FORCE_IPV4="",'
echo '  ETH0_DNS="8.8.8.8",'
echo '  ETH0_GATEWAY="185.66.68.1",'
echo '  ETH0_GATEWAY6="",'
echo '  ETH0_IP="185.66.68.5",'
echo '  ETH0_IP6="",'
echo '  ETH0_IP6_ULA="",'
echo '  ETH0_MAC="02:00:b9:42:44:05",'
echo '  ETH0_MASK="255.255.255.128",'
echo '  ETH0_MTU="",'
echo '  ETH0_NETWORK="",'
echo '  ETH0_SEARCH_DOMAIN="",'
echo '  ETH0_VROUTER_IP="",'
echo '  ETH0_VROUTER_IP6="",'
echo '  ETH0_VROUTER_MANAGEMENT="",'
echo '  NETWORK="YES",'
echo '  SSH_PUBLIC_KEY="",'
echo '  TARGET="hda" ]'
echo 'CPU="1"'
echo 'GRAPHICS=['
echo '  LISTEN="0.0.0.0",'
echo '  PORT="6029",'
echo '  TYPE="VNC" ]'
echo 'MEMORY="1024"'
echo 'TEMPLATE_ID="43"'
echo 'VCPU="1"'
echo 'VMID="129"'